### ISSUE TITLE
Mount all N/W drives at once and mount all these drives as a single partition

### ISSUE THREAD

**Issue by paladhamma** [palasangha/Treasures-Of-Dhamma#16]
`mount` and `mhddfs`

**Comment by paladhamma** [comment]
1. `sudo nano /etc/fstab`

Add the following code:

    `#share network drive
    //172.12.0.6/Treasures_Of_Dhamma /mnt/Treasures_Of_Dhamma cifs username=***,domain=***,password=***,uid=33,file_mode=0444,dir_mode=0444 00
    //172.12.0.6/TOD_Database /mnt/TOD_Database cifs username=***,domain=***,password=***,uid=33,file_mode=0444,dir_mode=0444 00
    //172.12.0.6/C1PalaPhotoVideoShoot /mnt/C1PalaPhotoVideoShoot cifs username=***,domain=***,password=***,uid=33,file_mode=0444,dir_mode=0444 00
    //172.12.0.6/Arch_processeddata /mnt/Arch_processeddata cifs username=***,domain=***,password=***,uid=33,file_mode=0444,dir_mode=0444 00
    //172.12.0.6/Diaries_Of_Dhamma /mnt/Diaries_Of_Dhamma cifs username=***,domain=***,password=***,uid=33,file_mode=0444,dir_mode=0444 00
    //172.12.0.6/Images_Of_Dhamma /mnt/Images_Of_Dhamma cifs username=***,domain=***,password=***,uid=33,file_mode=0444,dir_mode=0444 00
    //172.12.0.6/Images_Of_Dhamma_2 /mnt/Images_Of_Dhamma_2 cifs username=***,domain=***,password=***,uid=33,file_mode=0444,dir_mode=0444 00
    //172.12.0.6/Letters_Of_Dhamma /mnt/Letters_Of_Dhamma cifs username=***,domain=***,password=***,uid=33,file_mode=0444,dir_mode=0444 00
    //172.12.0.6/Print_Media_Of_Dhamma /mnt/Print_Media_Of_Dhamma cifs username=***,domain=***,password=***,uid=33,file_mode=0444,dir_mode=0444 00
    //172.12.0.6/Videos_Of_Dhamma /mnt/Videos_Of_Dhamma cifs username=***,domain=***,password=***,uid=33,file_mode=0444,dir_mode=0444 00
    //172.12.0.6/VRID2PalaNew /mnt/VRID2PalaNew cifs username=***,domain=***,password=***,uid=33,file_mode=0444,dir_mode=0444 00
    
    #mhddfs#/mnt/Network_Drives/Arch_processeddata,/mnt/Network_Drives/Treasures_Of_Dhamma,/mnt/Network_Drives/TOD_Database,/mnt/Network_Drives/C1PalaPhotoVideoShoot,/mnt/Network_Drives/Diaries_Of_Dhamma,/mnt/Network_Drives/Images_Of_Dhamma,/mnt/Network_Drives/Images_Of_Dhamma_2,/mnt/Network_Drives/Letters_Of_Dhamma,/mnt/Network_Drives/Print_Media_Of_Dhamma,/mnt/Network_Drives/Videos_Of_Dhamma /mnt/172.12.0.6 fuse nonempty,defaults,allow_other 0 0`
    
Note: 
1. One can add more drives or edit drive names as per the need, also please add your username, domain, and password. 
2. The file_mode and dir_mode can be changed - currently, it's the read-only mode. 
3. To mount as a single partition `mhddfs` command is used, here one can add more drives if required. 
4. Change in destination path can be done as well.

2. Save the `/etc/fstab` file using `Ctrl+X`, press Y. 

3. Run `sudo mount -a` -> This will mount all drives.

Note: To unmount all drives - 

First, unmount merged drives then unmount all mounted drives (reverse step as we had mounted drives first then merged it).
1. Use `sudo umount /path/to/mounted path`. Eg: `sudo umount /mnt/Network_Drives/*`.
2. Do not use `sudo umount -a` as this will unmount all system drives too. If by mistake this is executed type `sudo reboot` to restart and all system drives will be mounted. Also do not use `sudo umount -l /` as it unmounts sudo's root privilege. If done then restart server from IT then `ssh to 121 from 120`, type `su` enter root pass and type `chmod u+s /usr/bin/sudo`. This will recover.

**Comment by aryalsujay** [comment]
Let me explain in detail what we achieved in local deployment. (This might be long)
We have a collection of images, documents, audios, videos. All of these individual collections are in separate N/W drives. Images are allocated a single N/W drive, and so on for remaining item types.
In the AMI set, in the images field column we wanted to mention the link of the image/documents from our internal server (N/W drive(s)) directly so that the ADO displays the image directly from the N/W drive(s) that is created after pushing the AMI set.
So for this, first we mounted our N/W drive to our local archipelago server. How? Let me explain those steps here (Note: We are using Ubuntu 20.04.5 LTS (Focal Fossa) - Linux distro).
cd /mnt;
sudo mkdir <Mount_NW_drives>; : Create a new directory to mount our drives inside this.
cd <Mount_NW_drives>;
sudo mkdir <Images_Collection> : Create a new directory for Images Collection & so on for documents, audios, videos.
sudo nano /etc/fstab;
Added the following codes to mount all drives on boot:
#share network drive
//<local_IP-192.xx.x.xx>/<Images_Collection> /mnt/<Mount_NW_drives> cifs username=***,domain=***,password=***,uid=33,file_mode=0755,dir_mode=0755 00
//<local_IP-192.xx.x.xx>/<Documents_Collection> /mnt/<Mount_NW_drives> cifs username=***,domain=***,password=***,uid=33,file_mode=0755,dir_mode=0755 00
//<local_IP-192.xx.x.xx>/<Audios_Collection> /mnt/<Mount_NW_drives> cifs username=***,domain=***,password=***,uid=33,file_mode=0755,dir_mode=0755 00
//<local_IP-192.xx.x.xx>/<Videos_Collection> /mnt/<Mount_NW_drives> cifs username=***,domain=***,password=***,uid=33,file_mode=0755,dir_mode=0755 00
Saved the /etc/fstab file using Ctrl+X, press Y.
Ran sudo mount -a -> This will mount all the N/W drives at once.
  4. After the mounting process was completed, we wanted these drives to be linked to our minio bucket "archipelago" so that we can add the link to the image/documents... in the images field.
 (E.g.: s3://<Images_Collection>/Images/jpg/1900_01_IN.jpg ).
  5. So, for linking our drives to minio, we edited the docker-compose.ymlfile.
 minio:
    container_name: esmero-minio
    restart: always
    image: minio/minio:RELEASE.2022-06-11T19-55-32Z
    volumes:
      - /mnt/<Mount_NW_drives>:/data:cached
      #- ${ARCHIPELAGO_ROOT}/data_storage/minio-data:/data:cached
    # Uncomment for Minio level caches  - /mnt/data/cache:/cache
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - host-net
      - esmero-net
    environment:
      MINIO_HTTP_TRACE: /tmp/minio-log.txt
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
      #MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      #MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
  #   MINIO_CACHE_DRIVES: /cache
  #   MINIO_CACHE_EXCLUDE: "*.json,*.jpg,*.jpeg"
  #   MINIO_CACHE_QUOTA: 80
  #   MINIO_CACHE_RANGE: "off"
  #   MINIO_CACHE_AFTER: 3
  #   MINIO_CACHE_WATERMARK_LOW: 70
  #   MINIO_CACHE_WATERMARK_HIGH: 90
    #command: gateway s3 https://s3.amazonaws.com/ --console-address ":9001"
As seen above, we commented the default data_storage location and added a new location for minio bucket here.
Note: So, first we mounted our drives in <Mount_NW_drives> directory and added this path in docker-compose.yml to connect our mounted N/W drives to the minio bucket "archipelago". Thus, all files/folders of N/W drives are listed inside this directory <Mount_NW_drives>.
  6. Coming to minio console, on opening the bucket "archipelago" the drive names are visible - but do not work, on clicking on any one of the folder nothing happens. So, on researching found that only one N/W drive can be mounted to a single bucket.
  7. So, Searched for options on how can we get minio to talk to multiple drives. And found a solution using mhddfscommand (Mhddfs – Combines Several Smaller Partitions into One Large Virtual Storage).
https://www.tecmint.com/combine-partitions-into-one-in-linux-using-mhddfs/
  8. So, merged all the N/W drives into one virtual storage using mhddfs command.
But first, created a directory where we can combine all mounted drives. Since we already had mounted drives in <Mount_NW_drives> folder. Now, we need one more folder in /mnt where we can combine already mounted drives in <Mount_NW_drives> folder and create a single partition.
For that, follow below steps:
sudo mkdir /mnt/<merged>; : Here, in this folder, we will merge all the drives.
sudo nano /etc/fstab; : Add mhddfs command
#share network drive
//<local_IP-192.xx.x.xx>/<Images_Collection> /mnt/<Mount_NW_drives> cifs username=***,domain=***,password=***,uid=33,file_mode=0755,dir_mode=0755 00
//<local_IP-192.xx.x.xx>/<Documents_Collection> /mnt/<Mount_NW_drives> cifs username=***,domain=***,password=***,uid=33,file_mode=0755,dir_mode=0755 00
//<local_IP-192.xx.x.xx>/<Audios_Collection> /mnt/<Mount_NW_drives> cifs username=***,domain=***,password=***,uid=33,file_mode=0755,dir_mode=0755 00
//<local_IP-192.xx.x.xx>/<Videos_Collection> /mnt/<Mount_NW_drives> cifs username=***,domain=***,password=***,uid=33,file_mode=0755,dir_mode=0755 00

#Combines Several Smaller Partitions into One Large Virtual Storage
#mhddfs#/mnt/<Mount_NW_drives>/<Images_Collection>,/mnt/<Mount_NW_drives>/<Documents_Collection>,/mnt/<Mount_NW_drives>/<Audios_Collection>,/mnt/<Mount_NW_drives>/<Videos_Collection> /mnt/<merged> fuse nonempty,defaults,allow_other 0 0
sudo mount -a;
  9. Now, all the mounted drives that were mounted individually in <Mount_NW_drives> folder have been merged into <merged> folder.
  10. Again, for linking our drives to minio, we edited the docker-compose.yml file.
 minio:
    container_name: esmero-minio
    restart: always
    image: minio/minio:RELEASE.2022-06-11T19-55-32Z
    volumes:
      - /mnt/<merged>:/data:cached
      #- ${ARCHIPELAGO_ROOT}/data_storage/minio-data:/data:cached
    # Uncomment for Minio level caches  - /mnt/data/cache:/cache
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - host-net
      - esmero-net
    environment:
      MINIO_HTTP_TRACE: /tmp/minio-log.txt
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
      #MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      #MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
  #   MINIO_CACHE_DRIVES: /cache
  #   MINIO_CACHE_EXCLUDE: "*.json,*.jpg,*.jpeg"
  #   MINIO_CACHE_QUOTA: 80
  #   MINIO_CACHE_RANGE: "off"
  #   MINIO_CACHE_AFTER: 3
  #   MINIO_CACHE_WATERMARK_LOW: 70
  #   MINIO_CACHE_WATERMARK_HIGH: 90
    #command: gateway s3 https://s3.amazonaws.com/ --console-address ":9001"
Note:
a. So, we are using the folder where merged drives are present i.e. in  <merged> directory, and added this path in docker-compose.yml to connect our mounted N/W drives to the minio bucket "archipelago". Thus, all files/folders of merged N/W drives are listed inside this directory <merged>.
b. Also, when we open the <merged> folder all the folders/ files of 4 N/W drives are mixed. So, just to segregate our drives inside, E.g.: For Images_Collection drive, created a folder with the same name as the drive Images_Collection and moved all the contents of the drive inside this newly created folder (We are just adding a layer of a folder here). Thus, in place of seeing all mixed-up files/folders of different N/W drives, we are able to view folders drive-wise.
c. Also, to connect our minio bucket to merged drives, a folder has to be created here with the same name as the bucket name.
E.g.: cd /mnt/<merged>;
sudo mkdir archipelago;
To change ownership and r/w permissions:
cd ..
sudo chown -R www-data <merged>;
sudo chmod -R 755 <merged>;
d. "archipelago" folder has been created in all of our N/W drives as any edit/change we do in <merged> folder reflects in all the N/W drives (since they have been merged...)
e. Again, to add all of our N/W drives content to the bucket "archipelago", move (E.g.: ) the Images_Collection folder to archipelago folder. This way one more layer gets added through which multiple drives content can be accessed via minio bucket. Solved!
To Sum up, we mounted multiple N/W drives to the local archipelago server. Edited minio data_storage location and connected drives to minio bucket. But since a bucket is only able to handle one mounted drive, so we merged all drives into one single virtual storage folder and carried the same step as above (editing work mainly). And finally got minio to talk to this single virtual storage where we have all of our drives in a structured manner.
So, this was about connecting multiple drives to one minio bucket.
Coming to AMI set creation, import, node creation.
An AMI set created with images, documents ... fields for images, documents, audios, videos.
In images field added s3://<Images_Collection>/Images/jpg/1900_01_IN.jpg , documents field added s3://<Documents_Collection>/Documents/jpg/1900_01_IN.pdf and so on for rest.
Note: the path you see for images are being taken from Image_Collection N/W drive and same for documents,...
 3. On Uploading this AMI set, a new node is created, images, documents are fetched from the existing drive, and are displayed in that ADO. JSON files are created in dostorage with all metadata but the image is not being stored/copied.
This is what we achieved in local deployment. As explained yesterday, looking for an option to achieve the same in live deployment.
[@Diego Pino](https://archipelagocommons.slack.com/team/UQKP7EDUN)
 Tried to document the steps out roughly, might need more editing... Also, wanted to explain in detail.
Out of the 3 options you mentioned yesterday, the 3rd one is apt (also as you advised it). So, on implementing it, edited the docker-compose.yml file (PFA below).
Added /mnt/minio:/var/www/mount/:cached .Here, have merged all drives in minio folder. The mount folder is empty, just created it. After this, created an AMI set and in images field added /mnt/minio/archipelago(bucketname)/Images/jpg/1900_01.jpg . Imported this but Sorry, for ADO with UUID:6f2aeb5b-c3f2-4dcf-b73f-27ae4f83ff5e, File <...>.jpg at column images was not found. Skipping. Please check your CSV for set 10.
Also, tried using s3://Images/jpg... format just in case to check. Both of these do not work.
Ha! Thanks for reading!:slightly_smiling_face:
